from src.prompts.kpi_logic_prompts import KPI_SQL_NORMALIZATION_PROMPT, KPI_SQL_NORMALIZER_SYSTEM_PROMPT
from src.prompts.mapping_prompts import MAPPING_AGENT_PROMPT, MAPPING_AGENT_SYSTEM_PROMPT
from src.prompts.requirement_prompts import REQUIREMENT_AGENT_PROMPT, REQUIREMENT_AGENT_SYSTEM_PROMPT
from src.prompts.sql_prompts import ANALYZE_PROMPT, GENERATE_TESTS_PROMPT, SQL_AGENT_SYSTEM_PROMPT
from src.prompts.test_case_prompts import TEST_CASE_AGENT_SYSTEM_PROMPT, TEST_CASE_GENERATION_PROMPT

__all__ = [
    "ANALYZE_PROMPT",
    "GENERATE_TESTS_PROMPT",
    "KPI_SQL_NORMALIZATION_PROMPT",
    "KPI_SQL_NORMALIZER_SYSTEM_PROMPT",
    "MAPPING_AGENT_PROMPT",
    "MAPPING_AGENT_SYSTEM_PROMPT",
    "REQUIREMENT_AGENT_PROMPT",
    "REQUIREMENT_AGENT_SYSTEM_PROMPT",
    "SQL_AGENT_SYSTEM_PROMPT",
    "TEST_CASE_AGENT_SYSTEM_PROMPT",
    "TEST_CASE_GENERATION_PROMPT",
]
